/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StaticBuffering (https://sketchfab.com/StaticBuffering)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-notice-board-7054cc045dd04d79bb76e158803e9b47
Title: Low Poly Notice Board
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Board(props) {
  const { nodes, materials } = useGLTF("./low_poly_notice_board.glb");
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, 0]} position={[0.2, 0.4, -0.5]}>
      <group scale={0.05}>
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_board_frame_0.geometry}
          material={materials.board_frame}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_board_center_0.geometry}
          material={materials.board_center}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_Pin_Blue_0.geometry}
          material={materials.Pin_Blue}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_PushPin_Red_0.geometry}
          material={materials.PushPin_Red}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Notice_Board_PushPin_Metal_0.geometry}
          material={materials.PushPin_Metal}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./low_poly_notice_board.glb");
