/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: eucalyp555 (https://sketchfab.com/eucalyp555)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-plant-in-a-pot-e3a4d0c168954ced9e3702c14b986046
Title: Low Poly Plant in a pot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant(props) {
  const { nodes, materials } = useGLTF('./low_poly_plant_in_a_pot.glb')
  return (
    <group {...props} dispose={null} scale={0.05} position={[0, 0, -0.4]}>
      <group position={[0, 0.852, 0]} scale={0.854}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.ceramique}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.dirt}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.bark_i_dunno_i_guess_thats_how_its_called}
        position={[0, 1.411, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.bark_i_dunno_i_guess_thats_how_its_called}
        position={[-0.037, 1.411, -0.123]}
        rotation={[0, -0.9, 0]}
        scale={0.69}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.bark_i_dunno_i_guess_thats_how_its_called}
        position={[0.02, 1.525, -0.052]}
        rotation={[0.987, 1.499, -1.008]}
        scale={0.291}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.leaf}
        position={[0.365, 2.984, -0.105]}
        rotation={[0, 1.146, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.leaf}
        position={[0.144, 5.128, 0.629]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.leaf}
        position={[-0.596, 4.4, -0.245]}
        rotation={[-2.687, 1.381, 2.411]}
        scale={0.908}
      />
    </group>
  )
}

useGLTF.preload('./low_poly_plant_in_a_pot.glb')