/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lucasalic99 (https://sketchfab.com/lucasalic99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-table-low-poly-7bec46eba468479c8d3aca08b1b41690
Title: Desk / Table Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Table(props) {
  const { nodes, materials } = useGLTF("./desk__table_low_poly.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={0.07}
      rotation={[0, Math.PI / 2, 0]}
      position={[0.03, 0, -0.02]}
    >
      <group position={[1.783, 1.016, 0]} scale={[0.072, 1.136, 1.255]}>
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[1.692, 1.378, 1.023]}
        rotation={[-0.012, 0.049, -1.545]}
        scale={0.136}
      >
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./desk__table_low_poly.glb");
